services:
  connector-misp-feed-botvrij:
    image: opencti/connector-misp-feed:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_BACKEND_URL}
      - OPENCTI_TOKEN=${MISP_BOTVRIJ_TOKEN_CONNECTOR}
      - CONNECTOR_ID=${MISP_BOTVRIJ_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MISP Feed (Botvrij)"
      - CONNECTOR_SCOPE=misp-feed-botvrij
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - MISP_FEED_URL=https://www.botvrij.eu/data/feed-osint/
      - MISP_FEED_SSL_VERIFY=true # Required
      - MISP_FEED_IMPORT_FROM_DATE=2020-01-01 # Required, import all event from this date
      - MISP_FEED_CREATE_REPORTS=true # Required, create report for MISP event
      - MISP_FEED_REPORT_TYPE=misp-botvrij-event
      - MISP_FEED_CREATE_INDICATORS=true # Required, create indicators from attributes
      - MISP_FEED_CREATE_OBSERVABLES=true # Required, create observables from attributes
      - MISP_FEED_CREATE_OBJECT_OBSERVABLES=true # Required, create text observables for MISP objects
      - MISP_FEED_CREATE_TAGS_AS_LABELS=true # Optional, create tags as labels (sanitize MISP tag to OpenCTI labels)
      - MISP_FEED_GUESS_THREAT_FROM_TAGS=true # Optional, try to guess threats (threat actor, intrusion set, malware, etc.) from MISP tags when they are present in OpenCTI
      - MISP_FEED_AUTHOR_FROM_TAGS=false # Optional, map creator:XX=YY (author of event will be YY instead of the author of the event)
      - MISP_FEED_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_FEED_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=false #  Optional, import unsupported observable as x_opencti_text
      - MISP_FEED_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT_TRANSPARENT=false #  Optional, import unsupported observable as x_opencti_text just with the value
      - MISP_FEED_IMPORT_WITH_ATTACHMENTS=true # Optional, try to import a PDF file from the attachment attribute
      - MISP_FEED_INTERVAL=240 # Required, in minutes
    restart: always
    networks:
      - opencti-network 
    depends_on:
      opencti-backend:
        condition: service_healthy

  connector-misp-feed:
    image: opencti/connector-misp-feed:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_BACKEND_URL}
      - OPENCTI_TOKEN=${MISP_CIRCL_TOKEN_CONNECTOR}
      - CONNECTOR_ID=${MISP_CIRCL_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MISP Feed (CIRCL)"
      - CONNECTOR_SCOPE=misp-feed-circl
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - MISP_FEED_URL=https://www.circl.lu/doc/misp/feed-osint/
      - MISP_FEED_SSL_VERIFY=true # Required
      - MISP_FEED_IMPORT_FROM_DATE=2020-01-01 # Required, import all event from this date
      - MISP_FEED_CREATE_REPORTS=true # Required, create report for MISP event
      - MISP_FEED_REPORT_TYPE=misp-circl-event
      - MISP_FEED_CREATE_INDICATORS=true # Required, create indicators from attributes
      - MISP_FEED_CREATE_OBSERVABLES=true # Required, create observables from attributes
      - MISP_FEED_CREATE_OBJECT_OBSERVABLES=true # Required, create text observables for MISP objects
      - MISP_FEED_CREATE_TAGS_AS_LABELS=true # Optional, create tags as labels (sanitize MISP tag to OpenCTI labels)
      - MISP_FEED_GUESS_THREAT_FROM_TAGS=true # Optional, try to guess threats (threat actor, intrusion set, malware, etc.) from MISP tags when they are present in OpenCTI
      - MISP_FEED_AUTHOR_FROM_TAGS=false # Optional, map creator:XX=YY (author of event will be YY instead of the author of the event)
      - MISP_FEED_IMPORT_TO_IDS_NO_SCORE=40 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_FEED_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=false #  Optional, import unsupported observable as x_opencti_text
      - MISP_FEED_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT_TRANSPARENT=false #  Optional, import unsupported observable as x_opencti_text just with the value
      - MISP_FEED_IMPORT_WITH_ATTACHMENTS=true # Optional, try to import a PDF file from the attachment attribute
      - MISP_FEED_INTERVAL=90 # Required, in minutes
    restart: always
    networks:
      - opencti-network 
    depends_on:
      opencti-backend:
        condition: service_healthy

  connector-misp-feed-cert-fr:
    image: opencti/connector-misp-feed:${OPENCTI_VERSION}
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_BACKEND_URL}
      - OPENCTI_TOKEN=${MISP_FEED_CERT_FR_ID_TOKEN_CONNECTOR}
      - CONNECTOR_ID=${MISP_FEED_CERT_FR_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MISP Feed (CERT-FR)"
      - CONNECTOR_SCOPE=misp-cert-fr-feed
      - CONNECTOR_CONFIDENCE_LEVEL=20 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_FEED_URL=https://misp.cert.ssi.gouv.fr/feed-misp/
      - MISP_FEED_SSL_VERIFY=true # Required
      - MISP_FEED_IMPORT_FROM_DATE=2018-01-01 # Required, import all event from this date
      - MISP_FEED_CREATE_REPORTS=true # Required, create report for MISP event
      - MISP_FEED_REPORT_TYPE=misp-event
      - MISP_FEED_CREATE_INDICATORS=true # Required, create indicators from attributes
      - MISP_FEED_CREATE_OBSERVABLES=true # Required, create observables from attributes
      - MISP_FEED_CREATE_OBJECT_OBSERVABLES=true # Required, create text observables for MISP objects
      - MISP_FEED_IMPORT_TO_IDS_NO_SCORE=30 # Optional, use as a score for the indicator/observable if the attribute to_ids is no
      - MISP_FEED_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=false #  Optional, import unsupported observable as x_opencti_text
      - MISP_FEED_IMPORT_WITH_ATTACHMENTS=yes # Optional, try to import a PDF file from the attachment attribute
      - MISP_FEED_INTERVAL=120 # Required, in minutes
    restart: always
    networks:
      - opencti-network 
    depends_on:
      opencti-backend:
        condition: service_healthy

networks:
  opencti-network:
    driver: bridge

